#!/usr/bin/env node

import { cp, lstat, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { parseArgs } from "node:util";

const TOOL_ROOT = import.meta.dirname;
const DEFAULT_CONFIG = path.join(TOOL_ROOT, "study-config.json");
const DEFAULT_OUTPUT = path.join(TOOL_ROOT, "unpacked");
const CONFIG_SCHEMA_VERSION = "storyvr-study-extension-config/v2";
const OUTPUT_MARKER = ".storyvr-study-extension-output";

export function validateStudyConfig(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError("The study extension config must be a JSON object.");
  }
  if (value.schemaVersion !== CONFIG_SCHEMA_VERSION) {
    throw new TypeError(`Unsupported study extension config: ${String(value.schemaVersion || "missing")}.`);
  }
  const studyConfigId = safeToken(value.studyConfigId, 80);
  if (!studyConfigId) throw new TypeError("studyConfigId is required.");
  const controllerPages = validateControllerPages(value.controllerPages);
  const originalPageConsent = validateOriginalPageConsent(value.originalPageConsent);
  if (!controllerPages.length) throw new TypeError("At least one StoryVR controller page is required.");
  return {
    schemaVersion: CONFIG_SCHEMA_VERSION,
    studyConfigId,
    displayName: cleanText(value.displayName, 120) || studyConfigId,
    controllerPages,
    originalPageConsent,
  };
}

export function createManifest(config) {
  const valid = validateStudyConfig(config);
  return {
    manifest_version: 3,
    name: `StoryVR Study Logger - ${valid.displayName}`,
    version: "0.3.0",
    minimum_chrome_version: "114",
    description: "Collects local interactions on original-story tabs that the researcher explicitly authorizes and merges them with StoryVR.",
    incognito: "not_allowed",
    permissions: ["storage", "activeTab", "scripting"],
    background: {
      service_worker: "service-worker.js",
      type: "module",
    },
    action: {
      default_title: "StoryVR study logger",
      default_popup: "popup.html",
    },
    content_scripts: [
      {
        matches: valid.controllerPages.flatMap(manifestPatterns),
        js: ["controller-content.js"],
        run_at: "document_start",
        all_frames: false,
        match_about_blank: false,
        match_origin_as_fallback: false,
        world: "ISOLATED",
      },
    ],
    content_security_policy: {
      extension_pages: "script-src 'self'; object-src 'self'",
    },
  };
}

export async function buildStudyExtension({
  configPath = DEFAULT_CONFIG,
  outputPath = DEFAULT_OUTPUT,
} = {}) {
  const config = validateStudyConfig(JSON.parse(await readFile(configPath, "utf8")));
  const manifest = createManifest(config);
  await validateOutputPath(outputPath, configPath);
  await rm(outputPath, { recursive: true, force: true });
  await mkdir(outputPath, { recursive: true });
  await cp(path.join(TOOL_ROOT, "src"), outputPath, { recursive: true });
  await writeFile(path.join(outputPath, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  await writeFile(path.join(outputPath, "study-config.json"), `${JSON.stringify(config, null, 2)}\n`);
  await writeFile(path.join(outputPath, OUTPUT_MARKER), "Generated by tools/storyvr-study-extension/build.mjs.\n");
  return { config, manifest, outputPath };
}

function validateControllerPages(value) {
  const fieldName = "controllerPages";
  if (!Array.isArray(value)) throw new TypeError(`${fieldName} must be an array.`);
  const pages = value.map((page, index) => {
    if (!page || typeof page !== "object" || Array.isArray(page)) {
      throw new TypeError(`${fieldName}[${index}] must be an object.`);
    }
    const origin = validControllerOrigin(page.origin);
    const pathPrefix = validPathPrefix(page.pathPrefix, fieldName, index);
    const pageKey = safeToken(page.pageKey, 80);
    if (!pageKey) throw new TypeError(`${fieldName}[${index}].pageKey is required.`);
    return { pageKey, origin, pathPrefix };
  });
  const keys = pages.map((page) => page.pageKey);
  if (new Set(keys).size !== keys.length) throw new TypeError(`${fieldName} pageKey values must be unique.`);
  return pages;
}

function validateOriginalPageConsent(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError("originalPageConsent must be an object.");
  }
  return {
    captureScrollDepth: value.captureScrollDepth !== false,
    allowControlLabelConsent: Boolean(value.allowControlLabelConsent),
  };
}

function validControllerOrigin(value) {
  let url;
  try {
    url = new URL(String(value || ""));
  } catch {
    throw new TypeError(`Invalid study page origin: ${String(value || "missing")}.`);
  }
  if (!['http:', 'https:'].includes(url.protocol) || url.origin !== String(value)) {
    throw new TypeError(`Study page origins must be exact HTTP(S) origins: ${String(value)}.`);
  }
  const loopback = ["localhost", "127.0.0.1", "[::1]"].includes(url.hostname);
  if (!loopback) {
    throw new TypeError(`StoryVR controller origins must be loopback-only: ${String(value)}.`);
  }
  return url.origin;
}

function validPathPrefix(value, fieldName, index) {
  if (typeof value !== "string" || !value.trim()) {
    throw new TypeError(`${fieldName}[${index}].pathPrefix must be explicit.`);
  }
  const result = value.trim();
  if (!result.startsWith("/") || /[?#*]/.test(result)) {
    throw new TypeError(`Invalid study page path prefix: ${result}.`);
  }
  return result;
}

function manifestPatterns(page) {
  if (page.pathPrefix === "/") return [`${page.origin}/*`];
  if (page.pathPrefix.endsWith("/")) return [`${page.origin}${page.pathPrefix}*`];
  return [
    `${page.origin}${page.pathPrefix}`,
    `${page.origin}${page.pathPrefix}/*`,
  ];
}

async function validateOutputPath(outputValue, configValue) {
  const outputPath = path.resolve(outputValue);
  const configPath = path.resolve(configValue);
  const sourcePath = path.join(TOOL_ROOT, "src");
  const buildsPath = path.join(TOOL_ROOT, "builds");
  const insideToolRoot = isInside(TOOL_ROOT, outputPath);
  const approvedToolOutput = outputPath === DEFAULT_OUTPUT || isInside(buildsPath, outputPath);
  if (outputPath === TOOL_ROOT
    || outputPath === sourcePath
    || isInside(sourcePath, outputPath)
    || isInside(outputPath, TOOL_ROOT)
    || isInside(outputPath, configPath)
    || (insideToolRoot && !approvedToolOutput)) {
    throw new TypeError(`Refusing unsafe extension output path: ${outputPath}`);
  }

  let outputStat = null;
  try {
    outputStat = await lstat(outputPath);
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  if (!outputStat) return;
  if (outputStat.isSymbolicLink() || !outputStat.isDirectory()) {
    throw new TypeError(`Extension output must be a real directory: ${outputPath}`);
  }
  if (outputPath === DEFAULT_OUTPUT) return;
  try {
    const marker = await readFile(path.join(outputPath, OUTPUT_MARKER), "utf8");
    if (!marker.startsWith("Generated by tools/storyvr-study-extension/build.mjs.")) throw new Error("invalid marker");
  } catch {
    throw new TypeError(`Refusing to replace an unmarked output directory: ${outputPath}`);
  }
}

function isInside(parent, child) {
  const relative = path.relative(parent, child);
  return Boolean(relative) && !relative.startsWith("..") && !path.isAbsolute(relative);
}

function safeToken(value, maximumLength) {
  return String(value || "")
    .replace(/[^a-zA-Z0-9_.:-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, maximumLength);
}

function cleanText(value, maximumLength) {
  const result = String(value || "").replace(/\s+/g, " ").trim();
  return result.length <= maximumLength ? result : `${result.slice(0, maximumLength - 1).trimEnd()}…`;
}

async function main() {
  const args = parseArgs({
    options: {
      config: { type: "string", default: DEFAULT_CONFIG },
      out: { type: "string", default: DEFAULT_OUTPUT },
    },
  });
  const result = await buildStudyExtension({
    configPath: path.resolve(args.values.config),
    outputPath: path.resolve(args.values.out),
  });
  const relative = path.relative(process.cwd(), result.outputPath) || ".";
  console.log(`Built StoryVR study extension: ${relative}`);
  console.log(`Approved controller pages: ${result.config.controllerPages.length}`);
  console.log("Original story access: explicit current-tab authorization");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error?.stack || error);
    process.exitCode = 1;
  });
}
